### PR TITLE
Bugs i12 i13 category fixed

### LINKED ISSUE #12: Modifying categories not working properly
**Given** the user changes an existing category
**However** the category does not change and the app throws errors

### PR DESCRIPTION
**Pull request by khamui**
issues fixed #12 #13

### CODE REVIEW

File: src/components/xltable.js [hunk 1]
```diff
@@ -96,18 +96,18 @@ export class Xltable {
 
   actionData(expPosition) {
     if (!expPosition) return false;
-    const updateData = this.data;
-    const newRow = {title: expPosition};
+    let updateData = this.data;
```
Comment (khamui) [inline src/components/xltable.js]: Addtional let updateData needed?

File: src/components/xltable.js [hunk 2]
```diff
@@ -96,18 +96,18 @@ export class Xltable {
 
   actionData(expPosition) {
```
Comment (khamui) [inline src/components/xltable.js]: argument expPosition needed? usage of direct binding variable possible?
