### PR TITLE
f-component-xltable: value field wrong type handling

### LINKED ISSUE #2: Fieldcontrol - eg only numbers allowed for value fields - temporarily highlight wrong field, currently permanent red
**Given** a user enters non-numeric characters into value fields
**Then** the field should remove the input and show the numeric value before

### LINKED ISSUE #3: Fieldcontrol - category field and value fields different permissions
**Given** the user interacts with category fields and value fields
**And** adds, copies, deletes and edits a field
**Then** the field type should allow different interactions
**However** cross field interactions should be restricted (from category to value and vice versa)

### PR DESCRIPTION
**Pull request by khamui**
fixed #2, fixed #3

### CODE REVIEW

File: src/components/xltable.js [hunk 1]
```diff
@@ -35,10 +34,16 @@ export class Xltable {
         {data: 'row2', type: 'numeric', numericFormat: this.numformat},
         {data: 'row3', type: 'numeric', numericFormat: this.numformat}
       ],
+      cells: function(row, col, prop) {
```
Comment (khamui) [inline src/components/xltable.js]: callback function, instead of function definition in object possible?

File: src/components/xltable.js [hunk 2]
```diff
@@ -35,10 +34,16 @@ export class Xltable {
...
+        let cellProperties = {};
+        cellProperties.invalidCellClassName = 'hilight__error-anim';
+        return cellProperties;
+      },
       licenseKey: 'non-commercial-and-evaluation'
     });
 
     this.hot.addHook('afterSelectionEnd', (row, col, row2, col2) => this.sendSelection(row, col, row2, col2));
+    this.hot.addHook('afterChange', (changes, event) => this.checkNumberType(changes, event));
     // this.hot.addHook('afterDeselect', () => this.sendSelection());
```
Comment (khamui) [inline src/components/xltable.js]: remove commented handler

File: src/components/xltable.js [hunk 3]
```diff
@@ -47,6 +52,14 @@ export class Xltable {
     this.expensePosition = this.data[row].title;
   }
 
+  checkNumberType(changes, event) {
+    for (let change of changes) {
+      if (typeof change[3] === 'number') return;
+      this.data[change[0]][change[1]] = change[2];
+      this.hot.render();
```
Comment (khamui) [inline src/components/xltable.js]: render manually triggered needed? Implicit possible?
